# Generated by Django 4.2.2 on 2023-06-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="projects/")),
                ("name", models.CharField(max_length=45)),
                ("link", models.CharField(blank=True, max_length=75)),
                ("motivation", models.TextField()),
                ("capabilities", models.TextField()),
                ("my_contributions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(max_length=35)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.project"
                    ),
                ),
            ],
        ),
    ]
